GCP_PROJECT             = 'GCP_PROJECT_ID'
GCS_BUCKET              = 'GCS_BUCKET_ID'
PUBSUB_SUBSCRIPTION_ID  = 'PUBSUB_SUBSCRIPTION_ID_FROM_WHERE_OBJECT_LIST_IS_PULLED'
PUBSUB_ERROR_TOP_ID     = 'PUBSUB_ERROR_TOP_ID'

AWS_S3_BUCKET               = 'AWS_S3_BUCKET'
STATUS_OK                   = [200]

MAX_MESSAGES_PER_BATCH = 1

NUM_THREADS = 4

VERBOSE_LOG = True
LOG_NAME    = 'storage_tansfer'
